name: Go Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          set -e
          docker build -t cecepwahyu/myapp-image .
          docker tag cecepwahyu/myapp-image:latest cecepwahyu/myapp-image:${{ github.sha }}
          docker push cecepwahyu/myapp-image:latest
          docker push cecepwahyu/myapp-image:${{ github.sha }}
